name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow pull request events but only for the dev branch
  push:
    branches: [ dev ]

env:
  MY_REPO: https://JoseBS:${{secrets.GITHUB_TOKEN}}@github.com/JoseBS/HelloBuild-QA-Test.git
  MASTER_REPO: https://github.com/JoseBS/HelloBuild-QA-Test.git
  MASTER_BRANCH: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.17
    
    - name: Install, Build and Deploy
      run: |
        ls -la
        cd ./img-search
        yarn install
        yarn build
        mv build/* ../dist
        cd ../dist
        ls -la
        git config user.name "JoseBS"
        git config user.email "juanjoseba98@gmail.com"
        git fetch
        git checkout main
        git merge dev --allow-unrelated-histories
        git push