name: Auto deploy

# Controls when the workflow will run
on:
  # Triggers the workflow pull request events but only for the dev branch
  push:
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.17
    
    - name: Install, Build and Deploy
      run: |
        cd ./img-search
        echo "Proyect"
        ls -la
        yarn install
        yarn build
        cd ..
        echo "Repo Root with old docs directory"
        ls -la
        rm -rf docs
        echo "Repo Root without docs directory"
        ls -la
        mkdir docs
        echo "Repo Root with new docs directory"
        ls -la
        cd docs
        echo "empty docs"
        ls -la
        cd ..
        echo "Repo root"
        ls -la
        cd ./img-search
        echo "Proyect"
        ls -la
        mv build/* ../docs
        cd ..
        echo "Repo root"
        ls -la
        git config user.name "JoseBS"
        git config user.email "juanjoseba98@gmail.com"
        git add .
        git commit -m "Auto deploy" -a
        git push
#Random change to make a new push